### PR TITLE
Replace PUT verb with PATCH

### LINKED ISSUE #3: Use PATCH instead of PUT for updating records
Currently, the adapter still follows the default REST adapter behaviour when updating records, which is to PUT the entire resource. A smarter, better approach would be to only serialize changes, and send the request as a PATCH. 

The request might look something like this:
```
PATCH /animals/123
Content-Type: application/json-patch+json

[
  {"op": "replace", "path": "/animals/0/name", "value": "Tomster"},
  {"op": "replace", "path": "/animals/0/links/friends", "value": ["124"]}
]
```

### PR DESCRIPTION
**Pull request by andrewbranch**
The [spec requires](http://jsonapi.org/format/#crud-updating) updating records be done with a PATCH request. Previously this adapter used PUT requests as per the default RESTAdapter. This PR remedies that.

The [spec also allows](http://jsonapi.org/format/#crud-updating-resource-attributes) for PATCH requests to be incremental, i.e. omitting unchanged properties from the request. However, this is not a requirement for compliance, and is a bit of a different beast, so I didn’t attempt to tackle it here. That would be a welcome addition, but this at least achieves compliance.

Fixes kurko/ember-json-api#3 insofar as spec compliance, although the original opener cited incremental updates as the reason for opening.

### CODE REVIEW

**Comment by michelegera** [comment]
:+1:

**Comment by eneuhauser** [comment]
I'm reviewing locally, but I think the method types for create, retrieve, update, and delete should be referenced from properties that could be overridden. Update should default to 'PATCH', but could be overridden with 'PUT' or 'POST' if necessary.

There may be cases where a given method is not available. If your application is backed by a CDN, they may restrict the use of certain verbs. I ran into an issue where [Akamai](http://www.akamai.com/) wasn't supporting the DELETE method. Similarly, certain CMS's may have restrictions. For [AEM](http://www.adobe.com/marketing-cloud/enterprise-content-management.html), POSTs are restricted to content creation within the authoring tool and can't be used with your API.

This is kind of a tangent / rant, but I've been recommending JSON API to a couple large companies that have come from a traditional WebService / SOAP background. They now have "RESTful" services because they return JSON, but all the really did was change their SOAP service from returning XML to JSON. Some of the concepts of JSON API have been a tough sell. In particular, the hypermedia aspect. Although that is a big aspect of JSON API, I feel the conventions are a good basis even if you're not doing full blown hypermedia support.

I've made some inroads and have some allies on the inside, but surprisingly, method type was a large sticking point. Previously, even retrieves were done via POST (don't laugh, I'm serious), but they will move to GET. Other method types are up in the air.

Unfortunately, we won't be using Ember with either of these clients I'm consulting on the API design, but if we did, we could use ember-json-api even if the server didn't respond with the resource links and if we could override the method types for the various actions.

**Comment by andrewbranch** [comment]
You definitely have some good points, but I think it comes down to asking what the goal of this package is. I assumed the goal was to give drop-in support for interacting with servers that conform to the JSON API specification. I don't see a need to add back doors specifically for nonconforming APIs. Of course, in the wild, if a user has an API that sort of almost conforms to the specification, it would still be easy enough to use this package and extend the provided adapter.

Ember preaches convention over configuration, and I think this is one of the ways that software moves forward. Not everyone will move forward at the same time—I certainly know what it's like to be stuck working with rusty old SOAP APIs—but this is more or less the bleeding edge: an Ember addon for an API specification that's still in release candidate stage. And I think supporting antipatterns, even well-loved ones, might be harmful in the long run. It feels like the kind of thing you'll end up deprecating later on.

Since the spec allows for using PUT to extend the base functionality already defined, I think the place for PUT is in mixins that extend the specification—not in this package.

**Comment by eneuhauser** [comment]
I'm rooted in the Java world and my JSON API server is a custom built Java implementation, so I am use to over configuring everything. I'm undecided whether this Rails style magic is good magic or black magic, so I'm treading lightly.

I initially felt that it was poor design to force a consumer of this library to copy the source of `updateRecord` function just to change one word. However, I realized a better place would be to override `ajaxOptions` and they could still be abstracted from some of the actual implementation details.

```
ajaxOptions: function(url, type, options) {
    var methodType = (type === 'PATCH') ? 'PUT' : type;
    return this._super(url, methodType, options);
}
```

Given this, I think your recommendation to impose the convention without over-architecting is better.

**Pull request merged**
